image: microsoft/dotnet:1.1.2-sdk

stages:
  - build
  - test
  - deploy

cache:
  key: ${CI_BUILD_REF_NAME}
  untracked: true

server:
  stage: build
  script:
    - dotnet restore
    - dotnet build
  tags:
    - docker

xunit:
  stage: test
  script:
    - cd SimCivil.Test
    - dotnet restore
    - dotnet test
  tags:
    - docker
