image: microsoft/dotnet:1.1

stages:
  - build
  - test
  - deploy

server:
  stage: build
  script:
    - dotnet restore
    - dotnet build
  only:
    - master
    - dev
  tags:
    - docker

xunit:
  stage: test
  script:
    - cd SimCivil.Test
    - dotnet test
  only:
    - master
    - dev
  tags:
    - docker
  cache:
    untracked: true